#pragma once

#include <rdsn/service_api.h>

DEFINE_THREAD_POOL_CODE(THREAD_POOL_META_SERVER)
DEFINE_THREAD_POOL_CODE(THREAD_POOL_REPLICATION)
DEFINE_THREAD_POOL_CODE(THREAD_POOL_LOCAL_APP)
DEFINE_THREAD_POOL_CODE(THREAD_POOL_REPLICATION_LONG)

#define MAKE_EVENT_CODE(x, pri) DEFINE_TASK_CODE(x, pri, CURRENT_THREAD_POOL)
#define MAKE_EVENT_CODE_AIO(x, pri) DEFINE_TASK_CODE_AIO(x, pri, CURRENT_THREAD_POOL)
#define MAKE_EVENT_CODE_RPC(x, pri) DEFINE_TASK_CODE_RPC(x, pri, CURRENT_THREAD_POOL)

// THREAD_POOL_DEFAULT
#define CURRENT_THREAD_POOL rdsn::THREAD_POOL_DEFAULT
MAKE_EVENT_CODE(LPC_MUTATION_LOG_PENDING_TIMER, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_AIO(LPC_ASYNC_READ_COMPLETE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_AIO(LPC_ASYNC_WRITE_COMPLETE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_REPLICA_STATE_CHANGE_NOTIFICATION, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_REPORT, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_TEST, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_TEST2, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_TEST3, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_TEST4, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_TEST, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_TEST_AGENT_WRITE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_TEST_AGENT_READ, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_AIO(LPC_AIO_TEST, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_AIO(LPC_AIO_IMMEDIATE_CALLBACK, rdsn::TASK_PRIORITY_COMMON)
#undef CURRENT_THREAD_POOL

// THREAD_POOL_META_SERVER
#define CURRENT_THREAD_POOL THREAD_POOL_META_SERVER
MAKE_EVENT_CODE_RPC(RPC_CM_CALL, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_PARTITIONS, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_NODE_PARTITIONS, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_UPDATE_PARTITION_CONFIGURATION, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_UPDATE_PARTITION_EXPECTNODES, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_CREATE_TABLE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_REMOVE_TABLE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_MASTER_CDT, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_PARTITION_META, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_ALL_TABLES, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_TABLE_STATUS, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_TABLE_CONFIGURATION, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_TABLE_SCHEMA, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_PRIMARY_PNINFO_BY_INDEX, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_CREATE_STATUS_TRACKER, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_DELETE_STATUS_TRACKER, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_STATUS_TRACKER, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_QUERY_STATUS_TRACKER_INFO, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_UPDATE_STATUS_TRACKER_INFO, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_WATCHDOG, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_UPDATE_METABLOCK, rdsn::TASK_PRIORITY_COMMON)

// [obsolete
MAKE_EVENT_CODE_RPC(RPC_CM_CREATE_APP, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CM_REMOVE_APP, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_CM_QUERY_NODE_PARTITIONS_SCATTER, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_CM_QUERY_NODE_PARTITIONS_GATHER, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_LBM_RUN, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_QUERY_PN_DECREE, rdsn::TASK_PRIORITY_COMMON)
//]
#undef CURRENT_THREAD_POOL

// THREAD_POOL_REPLICATION
#define CURRENT_THREAD_POOL THREAD_POOL_REPLICATION
MAKE_EVENT_CODE(LPC_MUTATION_PENDING_TIMER, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE(LPC_GROUP_CHECK, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_CM_DISCONNECTED_SCATTER, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE(LPC_QUERY_NODE_CONFIGURATION_SCATTER, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE(LPC_LEARN_REMOTE_DELTA_FILES_COMPLETED, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE(LPC_SIM_UPDATE_PARTITION_CONFIGURATION_REPLY, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_AIO(LPC_WRITE_REPLICATION_LOG, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_AIO(LPC_LERARN_REMOTE_DISK_STATE, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE(LPC_QUERY_CONFIGURATION_ALL, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_REPLICATION_CLIENT_WRITE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_CONFIG_PROPOSAL, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_QUERY_PN_DECREE, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_PREPARE, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_GROUP_CHECK, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_LEARN, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_LEARN_COMPLETITION_NOTIFY, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_LEARN_ADD_LEARNER, rdsn::TASK_PRIORITY_HIGH)
MAKE_EVENT_CODE_RPC(RPC_REMOVE_REPLICA, rdsn::TASK_PRIORITY_COMMON)
#undef CURRENT_THREAD_POOL

// THREAD_POOL_LOCAL_APP
#define CURRENT_THREAD_POOL THREAD_POOL_LOCAL_APP
MAKE_EVENT_CODE(LPC_WRITE, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE_RPC(RPC_REPLICATION_CLIENT_READ, rdsn::TASK_PRIORITY_COMMON)
#undef CURRENT_THREAD_POOL

// THREAD_POOL_REPLICATION_LONG
#define CURRENT_THREAD_POOL THREAD_POOL_REPLICATION_LONG
MAKE_EVENT_CODE(LPC_LEARN_REMOTE_DELTA_FILES, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_GARBAGE_COLLECT_LOGS_AND_REPLICAS, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_OPEN_REPLICA, rdsn::TASK_PRIORITY_COMMON)
MAKE_EVENT_CODE(LPC_CLOSE_REPLICA, rdsn::TASK_PRIORITY_COMMON)
#undef CURRENT_THREAD_POOL