/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "simple_kv_types.h"

namespace dsn { namespace replication { namespace application {


kv_pair::~kv_pair() throw() {
}


void swap(kv_pair &a, kv_pair &b) {
  using ::std::swap;
  swap(a.key, b.key);
  swap(a.value, b.value);
}

kv_pair::kv_pair(const kv_pair& other0) {
  key = other0.key;
  value = other0.value;
}
kv_pair& kv_pair::operator=(const kv_pair& other1) {
  key = other1.key;
  value = other1.value;
  return *this;
}
}}} // namespace
