TARGET=replication
INC_EXTRA = ../client_lib ../lib ../meta_server
LIB_EXTRA = dsn.replication dsn.replication.client dsn.replication.meta_server dsn.failure_detector
TYPE = EXE
include ../../../../scripts/makefile.common
