TARGET=rdsn.replication
INC_EXTRA = -I../client_lib -I../lib -I../meta_server
LIB_EXTRA = rdsn.replication rdsn.replication.client rdsn.replication.meta_server rdsn.failure_detector
TYPE = EXE
include ../../../../scripts/makefile.common
