TARGET=dsn.replication
INC_EXTRA = -I../client_lib -I../lib -I../meta_server
LIB_EXTRA = dsn.replication dsn.replication.client dsn.replication.meta_server dsn.failure_detector
TYPE = EXE
include ../../../../scripts/makefile.common
